# Generated by Django 4.1.7 on 2023-02-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('photo', models.ImageField(upload_to='uploads', verbose_name='Фото')),
                ('category', models.CharField(choices=[('bentoo cakes for diabetics', 'Bentoo Cakes For Diabetics'), ('bentoo cakes', 'Bentoo Cakes'), ('cake pops', 'Cake Pops'), ('cakes for diabetics', 'Cakes For Diabetics'), ('chocolate sweets', 'Chocolate Sweets'), ('classic cakes', 'Classic Cakes'), ('cupcakes for diabetics', 'Cupcakes For Diabetics'), ('cupcakes', 'Cupkaces'), ('isomalt lollipops', 'Isomalt Lollipops'), ('marmelade candies', 'Marmelade Candies'), ('painted gingerbread', 'Painted Gingerbread'), ('sugar lollipops', 'Sugar Lollipops'), ('empty', 'выберете категорию')], default='empty', max_length=70, verbose_name='Категория')),
                ('publication_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время публикации')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('slug', models.SlugField(verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Публикации',
                'ordering': ['-publication_time'],
            },
        ),
    ]
