# Generated by Django 4.1.7 on 2023-02-24 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='publication',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.photo', verbose_name='Фото'),
        ),
    ]
