# Generated by Django 4.1.7 on 2023-02-24 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_publication_photo_delete_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='photo',
            field=models.ImageField(upload_to='uploads/', verbose_name='Фото'),
        ),
    ]
