# Generated by Django 4.1.7 on 2023-02-25 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_publication_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='photo',
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/', verbose_name='Фото')),
                ('publication_link', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.publication')),
            ],
        ),
    ]
