# Generated by Django 4.1.7 on 2023-02-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_publication_photo1_publication_photo2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='category',
            field=models.CharField(choices=[('Бенто торты для диабетиков', 'Bentoo Cakes For Diabetics'), ('Бенто торты', 'Bentoo Cakes'), ('Кейк попсы', 'Cake Pops'), ('Торты для диабетиков', 'Cakes For Diabetics'), ('Шоколадные конфеты', 'Chocolate Sweets'), ('Классические торты', 'Classic Cakes'), ('Капкейки для диабетиков', 'Cupcakes For Diabetics'), ('Капкейки', 'Cupkaces'), ('Леденцы из изомальта', 'Isomalt Lollipops'), ('Мармелад', 'Marmelade Candies'), ('Расписные пряники', 'Painted Gingerbread'), ('Леденцы из сахара', 'Sugar Lollipops')], max_length=70, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='photo1',
            field=models.ImageField(default='plug.jpg', upload_to='photos/%Y/%B/', verbose_name='Фото 1'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='photo2',
            field=models.ImageField(default='plug.jpg', upload_to='photos/%Y/%B/', verbose_name='Фото 2'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='photo3',
            field=models.ImageField(default='plug.jpg', upload_to='photos/%Y/%B/', verbose_name='Фото 3'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='photo4',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%B/', verbose_name='Фото 4'),
        ),
    ]
