# Generated by Django 4.1.7 on 2023-03-03 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_prices_alter_publication_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='photo4',
            field=models.ImageField(blank=True, default='plug.jpg', null=True, upload_to='photos/%Y/%B/', verbose_name='Фото 4'),
        ),
    ]
