# Generated by Django 4.1.7 on 2023-03-03 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_publication_photo4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='photo4',
            field=models.ImageField(default='plug.jpg', upload_to='photos/%Y/%B/', verbose_name='Фото 4'),
        ),
    ]
