# Generated by Django 4.1.7 on 2023-03-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_publication_photo4'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fillings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Название')),
                ('description', models.TextField(max_length=250, verbose_name='Описание')),
                ('photo', models.ImageField(default='plug.jpg', upload_to='fillings/%Y/%B/', verbose_name='Фото 1')),
                ('date_and_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время публикации')),
            ],
            options={
                'verbose_name': 'Начинки',
                'verbose_name_plural': 'Начинки',
                'ordering': ['-date_and_time'],
            },
        ),
        migrations.AlterField(
            model_name='publication',
            name='photo1',
            field=models.ImageField(default='plug.jpg', upload_to='publications/%Y/%B/', verbose_name='Фото 1'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='photo2',
            field=models.ImageField(default='plug.jpg', upload_to='publications/%Y/%B/', verbose_name='Фото 2'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='photo3',
            field=models.ImageField(default='plug.jpg', upload_to='publications/%Y/%B/', verbose_name='Фото 3'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='photo4',
            field=models.ImageField(default='plug.jpg', upload_to='publications/%Y/%B/', verbose_name='Фото 4'),
        ),
    ]
