# Generated by Django 4.1.7 on 2023-03-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_fillings_alter_publication_photo1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='photo4',
            field=models.ImageField(blank=True, default='plug.jpg', null=True, upload_to='publications/%Y/%B/', verbose_name='Фото 4'),
        ),
    ]
