# Generated by Django 4.1.7 on 2023-03-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_publication_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
    ]
