# Generated by Django 4.1.7 on 2023-04-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_publication_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='conviviality',
            field=models.BooleanField(default=False, verbose_name='Праздничный?'),
        ),
    ]
