# Generated by Django 4.1.7 on 2023-04-01 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_publication_conviviality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='conviviality',
        ),
        migrations.AddField(
            model_name='publication',
            name='is_conviviality',
            field=models.BooleanField(default=False, verbose_name='Праздничный торт'),
        ),
    ]
