# Generated by Django 4.1.7 on 2024-01-08 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_prices_rolls_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prices',
            name='isomalt_lollipops_price',
        ),
    ]
