# Generated by Django 4.1.7 on 2024-01-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_publication_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='photo3',
            field=models.ImageField(blank=True, default='plug.jpg', null=True, upload_to='publications/%Y/%B/', verbose_name='Фото 3'),
        ),
    ]
