# Generated by Django 4.1.7 on 2024-01-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_certificates_delete_sertificates'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificatesFlowersForCakes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='flowers_for_cakes/', verbose_name='Фото')),
                ('title', models.CharField(max_length=70, verbose_name='Название')),
                ('description', models.TextField(max_length=250, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Цветок на торт',
                'verbose_name_plural': 'Цветы на торт',
            },
        ),
        migrations.AlterField(
            model_name='certificates',
            name='photo',
            field=models.ImageField(upload_to='certificates/', verbose_name='Фото'),
        ),
    ]
