# Generated by Django 4.1.7 on 2024-01-18 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_certificatesflowersforcakes_alter_certificates_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CertificatesFlowersForCakes',
            new_name='FlowersForCakes',
        ),
    ]
