# Generated by Django 4.1.7 on 2024-01-18 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_rename_certificatesflowersforcakes_flowersforcakes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flowersforcakes',
            name='description',
        ),
        migrations.RemoveField(
            model_name='flowersforcakes',
            name='title',
        ),
    ]
