# Generated by Django 5.0.3 on 2024-08-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_remove_flowersforcakes_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificates',
            options={'ordering': ['-publication_time'], 'verbose_name': 'Сертификат', 'verbose_name_plural': 'Сертификаты'},
        ),
        migrations.AlterModelOptions(
            name='flowersforcakes',
            options={'ordering': ['-publication_time'], 'verbose_name': 'Цветок на торт', 'verbose_name_plural': 'Цветы на торт'},
        ),
        migrations.AddField(
            model_name='certificates',
            name='publication_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default='2024-03-23 14:00', verbose_name='Дата и время публикации'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flowersforcakes',
            name='publication_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default='2024-03-23 14:00', verbose_name='Дата и время публикации'),
            preserve_default=False,
        ),
    ]
